Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-04, with the labels that each got.

#218 Remove MBEDTLS_PK_RSA_ALT
  ChangeLog.d/remove-pk-rsa-alt.txt
  drivers/builtin/include/mbedtls/pk.h
  drivers/builtin/src/pk.c
  drivers/builtin/src/pk_wrap.c
  drivers/builtin/src/pk_wrap.h
  include/psa/crypto_config.h
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved

#237 The LTS branch 2.28 is now EOL
  .github/pull_request_template.md
Labels: approved, needs-ci

#190 core: Update common.h to use GCC _Static_assert
  core/common.h
Labels: enhancement, needs-review, needs-ci

#214 Add migration guide and ChangeLog
  ChangeLog.d/removal-of-rng.txt
  docs/4.0-migration-guide/rng-removal.md
Labels: approved

#254 Don't call mbedtls_test_hook_error_add()
  drivers/builtin/include/mbedtls/error_common.h
  tests/suites/main_test.function
Labels: priority-high, size-xs, approved

#199 Add an internal function that returns the AES implementation
  ChangeLog.d/10012.txt
  drivers/builtin/include/mbedtls/aes.h
  drivers/builtin/src/aes.c
  programs/.gitignore
  programs/test/CMakeLists.txt
  programs/test/which_aes.c
Labels: approved

#251 Privatize part of psa_util.h
  ChangeLog.d/privatize-part-of-psa_util.txt
  core/psa_crypto.c
  drivers/builtin/include/mbedtls/psa_util.h
  drivers/builtin/src/pk_internal.h
  drivers/builtin/src/psa_crypto_ecp.c
  drivers/builtin/src/psa_util_internal.h
  tests/suites/test_suite_psa_crypto.function
Labels: size-s, priority-high, approved

#261 Constify cipher_wrap:mbedtls_cipher_base_lookup_table
  drivers/builtin/src/cipher_wrap.c
  drivers/builtin/src/cipher_wrap.h
Labels: priority-medium, size-xs, approved, needs-backports

#145 Plans for TF-PSA-Crypto legacy headers
  docs/architecture/0e-plans.md
Labels: priority-high, approved
