Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-05, with the labels that each got.

#253 [tf-psa-crypto] Restrict MBEDTLS_X509_RSASSA_PSS_SUPPORT
  ChangeLog.d/8154.txt
  drivers/builtin/include/mbedtls/pk.h
  drivers/builtin/src/pk.c
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: size-s, priority-high, approved

#238 removed p256-m.h from the install path and doxygen
  ChangeLog.d/make-p256-m-internal.txt
  drivers/p256-m/CMakeLists.txt
Labels: size-s, priority-high, approved

#272 Crypto: Test with GCC 15
  core/psa_crypto.c
  programs/test/tfpsacrypto_dlopen.c
  tests/suites/test_suite_psa_crypto.concurrent.data
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.persistent.data
Labels: priority-high, size-xs, approved, needs-backports

#247 Move public legacy headers to /include/mbedtls
  include/CMakeLists.txt
  include/mbedtls/asn1.h
  include/mbedtls/asn1write.h
  include/mbedtls/base64.h
  include/mbedtls/constant_time.h
  include/mbedtls/lms.h
  include/mbedtls/memory_buffer_alloc.h
  include/mbedtls/nist_kw.h
  include/mbedtls/pem.h
  include/mbedtls/pk.h
  include/mbedtls/platform.h
  include/mbedtls/platform_time.h
  include/mbedtls/platform_util.h
  include/mbedtls/psa_util.h
  include/mbedtls/threading.h
Labels: priority-high, size-xs, approved

#288 Prepare crypto for the OID module split
  ChangeLog.d/oid.txt
  drivers/builtin/include/mbedtls/crypto_oid.h
  drivers/builtin/include/mbedtls/oid.h
  drivers/builtin/src/oid.c
  drivers/builtin/src/pkcs5.c
  drivers/builtin/src/pkparse.c
  drivers/builtin/src/pkwrite.c
  drivers/builtin/src/rsa.c
  tests/suites/test_suite_md.function
  tests/suites/test_suite_oid.function
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_pkwrite.function
  tests/suites/test_suite_psa_crypto.function
Labels: priority-high, size-xs, approved

#265 Privatize functions and some types in hash headers
  drivers/builtin/include/mbedtls/md5.h
  drivers/builtin/include/mbedtls/ripemd160.h
  drivers/builtin/include/mbedtls/sha1.h
  drivers/builtin/include/mbedtls/sha256.h
  drivers/builtin/include/mbedtls/sha3.h
  drivers/builtin/include/mbedtls/sha512.h
Labels: priority-high, approved, api-break

#180 Move NIST_KW to PSA API
  ChangeLog.d/9382.txt
  drivers/builtin/include/mbedtls/cipher.h
  drivers/builtin/src/cipher.c
  drivers/builtin/src/cipher_wrap.c
  drivers/builtin/src/nist_kw.c
  include/mbedtls/nist_kw.h
  include/psa/crypto_adjust_config_dependencies.h
  include/psa/crypto_config.h
  include/tf-psa-crypto/check_config.h
  tests/scripts/components-build-system.sh
  tests/suites/test_suite_cipher.nist_kw.data
  tests/suites/test_suite_nist_kw.data
  tests/suites/test_suite_nist_kw.function
Labels: size-m, priority-high, approved, api-break

#271 Privatize functions and some types/macros in cipher primitive headers
  drivers/builtin/include/mbedtls/aes.h
  drivers/builtin/include/mbedtls/aria.h
  drivers/builtin/include/mbedtls/camellia.h
  drivers/builtin/include/mbedtls/chacha20.h
  drivers/builtin/include/mbedtls/chachapoly.h
  drivers/builtin/include/mbedtls/des.h
  drivers/builtin/include/mbedtls/poly1305.h
Labels: priority-high, approved, api-break

#295 Fix insufficient union initialization in contexts
  ChangeLog.d/union-initialization.txt
  core/psa_crypto.c
  drivers/builtin/src/psa_crypto_mac.c
Labels: size-s, needs-review, priority-high

#285 [tf-psa-crypto] Remove MBEDTLS_USE_PSA_CRYPTO from PK module
  drivers/builtin/src/pk.c
  drivers/builtin/src/pk_ecc.c
  drivers/builtin/src/pk_internal.h
  drivers/builtin/src/pk_wrap.c
  drivers/builtin/src/pk_wrap.h
  drivers/builtin/src/pkparse.c
  drivers/builtin/src/pkwrite.c
  drivers/builtin/src/pkwrite.h
  drivers/builtin/src/psa_util.c
  drivers/builtin/src/psa_util_internal.h
  include/mbedtls/pk.h
  include/tf-psa-crypto/check_config.h
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkwrite.function
Labels: priority-high, size-xs, approved

#200 Add a key confirmation attribute to the PAKE cipher suite
  ChangeLog.d/9323.txt
  include/psa/crypto_extra.h
Labels: enhancement, needs-review, priority-high, size-xs

#297 Remove encrypt/decrypt from PK
  ChangeLog.d/rm-pk-endecrypt.txt
  docs/4.0-migration-guide/pk-rm-crypt.md
  docs/4.0-migration-guide/rng-removal.md
  drivers/builtin/src/pk.c
  drivers/builtin/src/pk_wrap.c
  drivers/builtin/src/pk_wrap.h
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.data
  tests/suites/test_suite_pk.function
Labels: approved, api-break

#278 Remove mbedtls_pk_rsassa_pss_options
  include/mbedtls/pk.h
Labels: priority-high, size-xs, approved

#260 Move the inclusion of crypto_sizes.h and crypto_struct.h in crypto.h
  ChangeLog.d/move-crypto-struct-inclusion.txt
  include/psa/crypto.h
Labels: priority-medium, size-xs, approved
