Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-09, with the labels that each got.

#408 [tf-psa-crypto] Remove 224-bit curves (5/6)
  ChangeLog.d/ec-curves-support-removal.txt
  configs/ext/crypto_config_profile_medium.h
  core/tf_psa_crypto_check_config.h
  drivers/builtin/include/mbedtls/private/config_adjust_legacy_from_psa.h
  drivers/builtin/include/mbedtls/private/config_adjust_psa_superset_legacy.h
  drivers/builtin/include/mbedtls/private/ecp.h
  drivers/builtin/src/bignum_core.c
  drivers/builtin/src/crypto_oid.h
  drivers/builtin/src/ecp.c
  drivers/builtin/src/ecp_curves.c
  drivers/builtin/src/ecp_curves_new.c
  drivers/builtin/src/ecp_invasive.h
  drivers/builtin/src/oid.c
  drivers/builtin/src/psa_crypto_ecp.c
  drivers/builtin/src/psa_util.c
  include/psa/crypto_config.h
  include/psa/crypto_sizes.h
  include/psa/crypto_values.h
  tests/configs/crypto_config_test_driver_extension.h
  tests/scripts/components-compliance.sh
  tests/suites/test_suite_ecdh.data
  tests/suites/test_suite_ecdsa.data
  tests/suites/test_suite_ecp.data
  tests/suites/test_suite_ecp.function
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_psa_crypto.data
Labels: size-s, priority-high, approved

#446 Cleanup following the simplification of entropy and RNG options
  CMakeLists.txt
  core/psa_crypto.c
  core/psa_crypto_random_impl.h
  core/tf_psa_crypto_check_config.h
  core/tf_psa_crypto_common.h
  include/psa/crypto_adjust_config_synonyms.h
  include/psa/crypto_config.h
  tests/scripts/components-configuration-platform.sh
  tests/scripts/test_config_checks.py
  tests/suites/test_suite_config.crypto_combinations.data
Labels: priority-high, size-xs, approved

#451 Declare psa_can_do_cipher() publicly
  ChangeLog.d/psa_can_do_cipher.txt
  core/psa_crypto_core.h
  include/psa/crypto_extra.h
Labels: bug, priority-high, size-xs, approved, needs-backports

#458 crypto_config: fix documentation by removing mentions to unexisting build symbols
  include/psa/crypto_config.h
Labels: needs-review, needs-reviewer, priority-high, size-xs

#437 Create the 1.0 version of `md.h`
  ChangeLog.d/remove-md-heavy.txt
  drivers/builtin/src/hmac_drbg.c
  drivers/builtin/src/md.c
  drivers/builtin/src/pkcs5.c
  include/mbedtls/md.h
  tests/suites/test_suite_md.function
Labels: priority-high, approved

#463 Introduce TF-PSA-Crypto config version
  ChangeLog.d/config-version.txt
  include/psa/crypto_config.h
  include/tf-psa-crypto/build_info.h
Labels: priority-high, size-xs, approved

#468 Finalize pk.h
  ChangeLog.d/pk-simplify-rsa-padding.txt
  drivers/builtin/src/pk.c
  drivers/builtin/src/pk_rsa.c
  drivers/builtin/src/pk_wrap.h
  include/mbedtls/pk.h
  include/mbedtls/private/pk_private.h
  programs/fuzz/fuzz_privkey.c
Labels: size-s, priority-very-high, approved

#478 PK migration guide
  docs/4.0-migration-guide/pk.md
Labels: priority-very-high, approved

#484 Migration guide: PAKE
  docs/4.0-migration-guide/pake.md
Labels: priority-very-high, approved
