Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-07, with the labels that each got.

#342 Task remove aead ref
  programs/psa/aead_demo.c
  programs/psa/hmac_demo.c
Labels: size-xs, approved

#353 Create new mbedtls_pk_verify_ext function mbedtls_pk_verify_new
  drivers/builtin/src/pk.c
  include/mbedtls/pk.h
Labels: priority-high, size-xs, approved

#358 Rename mbedtls_pk_setup_opaque to mbedtls_pk_wrap_psa
  ChangeLog.d/rename-mbedtls_pk_setup_opaque.txt
  drivers/builtin/src/pk.c
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkwrite.function
Labels: priority-high, size-xs, approved

#270 Make aes_self_test use the new aes_get_implementation function
  drivers/builtin/src/aes.c
Labels: priority-high, size-xs, approved, needs-ci

#372 Remove deprecated items
  ChangeLog.d/remove-deprecated-items.txt
  drivers/builtin/src/asn1parse.c
  include/mbedtls/asn1.h
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
Labels: priority-high, size-xs, approved

#385 One crypto library
  core/CMakeLists.txt
  drivers/builtin/CMakeLists.txt
  drivers/everest/CMakeLists.txt
  drivers/p256-m/CMakeLists.txt
  pkgconfig/tfpsacrypto.pc.in
  tests/scripts/components-configuration-platform.sh
Labels: priority-high, approved

#356 Create Alias
  drivers/builtin/src/pk.c
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.function
Labels: size-s, priority-high, approved

#371 Remove options parameter from mbedtls_pk_verify_ext
  drivers/builtin/src/pk.c
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.function
Labels: priority-high, size-xs, approved

#387 check_config.h: move to core and test
  core/CMakeLists.txt
  core/tf_psa_crypto_check_config.h
  core/tf_psa_crypto_config.c
  drivers/builtin/src/ctr_drbg.c
  drivers/builtin/src/psa_crypto_rsa.c
  include/tf-psa-crypto/build_info.h
  scripts/config.py
  tests/scripts/components-basic-checks.sh
  tests/scripts/scripts_path.py
  tests/scripts/test_config_checks.py
Labels: size-s, priority-high, approved

#389 Remove PKCS12 module (MBEDTLS_PKCS12_C) and related test code
  ChangeLog.d/remove-pkcs12.txt
  configs/crypto-config-symmetric-only.h
  configs/ext/crypto_config_profile_medium.h
  drivers/builtin/include/mbedtls/config_adjust_legacy_crypto.h
  drivers/builtin/include/mbedtls/pkcs12.h
  drivers/builtin/src/crypto_oid.h
  drivers/builtin/src/oid.c
  drivers/builtin/src/pkcs12.c
  drivers/builtin/src/pkparse.c
  include/psa/crypto_config.h
  tests/suites/test_suite_pkcs12.data
  tests/suites/test_suite_pkcs12.function
  tests/suites/test_suite_pkparse.data
  tests/suites/test_suite_pkparse.function
Labels: size-s, priority-high, approved

#401 include: pk: use PSA_WANT instead of ECDSA_DETERMINISTIC for PK_ALG_ECDSA
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.data
Labels: bug, size-xs, priority-very-high, approved

#357 include private pk.h internally
  core/psa_crypto.c
  drivers/builtin/src/crypto_oid.h
  drivers/builtin/src/oid.c
  drivers/builtin/src/pk.c
  drivers/builtin/src/pk_ecc.c
  drivers/builtin/src/pk_internal.h
  drivers/builtin/src/pk_wrap.h
  drivers/builtin/src/pkparse.c
  drivers/builtin/src/pkwrite.c
  drivers/builtin/src/pkwrite.h
  drivers/builtin/src/psa_util.c
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.function
Labels: priority-high, size-xs, approved

#368 Remove duplicate definition.
  drivers/builtin/src/pk.c
  include/mbedtls/pk.h
Labels: priority-high, size-xs, approved
