Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-08, with the labels that each got.

#377 Remove alias
  drivers/builtin/src/pk.c
  include/mbedtls/pk.h
  tests/suites/test_suite_pk.function
Labels: priority-high, size-xs, approved

#196 Move the PAKE hash algorithm parameter into the alg id
  ChangeLog.d/9321.txt
  core/psa_crypto.c
  drivers/builtin/src/psa_crypto_pake.c
  include/psa/crypto_extra.h
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.data
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_metadata.data
  tests/suites/test_suite_psa_crypto_pake.data
  tests/suites/test_suite_psa_crypto_pake.function
Labels: enhancement, priority-high, size-xs, needs-preceding-pr, approved

#421 Fix whitespace in crypto_extra.h
  include/psa/crypto_extra.h
Labels: bug, priority-high, size-xs, single-reviewer

#396 Introduce MBEDTLS_PSA_CRYPTO_RNG_HASH (3/4)
  ChangeLog.d/rng_hash.txt
  core/psa_crypto_random_impl.h
  core/tf_psa_crypto_check_config.h
  drivers/builtin/include/mbedtls/ctr_drbg.h
  drivers/builtin/include/mbedtls/entropy.h
  include/psa/crypto_adjust_config_derived.h
  include/psa/crypto_config.h
  scripts/config.py
  tests/configs/crypto_config_test_driver.h
  tests/suites/test_suite_entropy.function
Labels: size-s, priority-high, approved

#420 Remove DES tests with an AES equivalent
  tests/suites/test_suite_ccm.data
  tests/suites/test_suite_cipher.padding.data
  tests/suites/test_suite_cmac.data
  tests/suites/test_suite_pem.data
  tests/suites/test_suite_pkcs5.data
Labels: size-s, priority-high, approved

#424 Remove `include/mbedtls/private` from Doxygen
  doxygen/tfpsacrypto.doxyfile.in
Labels: priority-high, size-xs, approved, component-docs

#189 Replace psa_pake_get_implicit_key() with psa_pake_get_shared_key()
  core/psa_crypto.c
  drivers/builtin/src/psa_crypto_pake.c
  include/psa/crypto_extra.h
  tests/include/test/psa_test_wrappers.h
  tests/src/psa_test_wrappers.c
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
  tests/suites/test_suite_psa_crypto_pake.function
Labels: enhancement, needs-review, priority-high, size-xs

#430 Create threading_internal.h
  drivers/builtin/src/threading.c
  drivers/builtin/src/threading_internal.h
Labels: priority-high, size-xs, approved
