Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-06, with the labels that each got.

#296 mbedtls: Check union initialization portably
  tests/suites/test_suite_psa_crypto.function
  tests/suites/test_suite_psa_crypto_driver_wrappers.function
Labels: size-s, priority-high, approved, needs-backports

#302 Remove requirment on MBEDTLS_PLATFORM_C for entropy
  configs/crypto-config-ccm-aes-sha256.h
  drivers/builtin/src/platform.c
  drivers/builtin/src/platform_util.c
  tests/configs/crypto_config_test_driver.h
Labels: bug, priority-high, size-xs, approved

#305 Doxygen: Only render public files
  doxygen/tfpsacrypto.doxyfile.in
Labels: priority-high, size-xs, approved

#312 Remove temporary SHA3 definition
  drivers/builtin/include/mbedtls/config_adjust_legacy_crypto.h
Labels: enhancement, priority-high, size-xs, approved

#184 Add ASN.1 function for parsing arbitrary precision integers
  ChangeLog.d/add-asn1-parsing-function.txt
  drivers/builtin/include/mbedtls/bignum.h
  drivers/builtin/src/asn1parse.c
  include/mbedtls/asn1.h
  tests/suites/test_suite_asn1parse.data
  tests/suites/test_suite_asn1parse.function
  tests/suites/test_suite_bignum_core.function
  tests/suites/test_suite_bignum_core.misc.data
Labels: size-s, priority-high, approved

#319 [tf-psa-crypto] Move Everest headers to a private subdirectory (2/2)
  drivers/builtin/include/mbedtls/ecdh.h
  drivers/everest/CMakeLists.txt
  drivers/everest/Makefile.inc
  drivers/everest/include/tf-psa-crypto/private/everest/Hacl_Curve25519.h
  drivers/everest/include/tf-psa-crypto/private/everest/everest.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlib.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlib/FStar_UInt128.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlib/FStar_UInt64_FStar_UInt32_FStar_UInt16_FStar_UInt8.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/c_endianness.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/builtin.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/callconv.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/compat.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/debug.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/target.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/types.h
  drivers/everest/include/tf-psa-crypto/private/everest/kremlin/internal/wasmsupport.h
  drivers/everest/include/tf-psa-crypto/private/everest/vs2013/Hacl_Curve25519.h
  drivers/everest/include/tf-psa-crypto/private/everest/x25519.h
  drivers/everest/library/everest.c
  drivers/p256-m/CMakeLists.txt
Labels: size-s, priority-high, approved

#322 Move mbedtls/build_info.h to tests
  CMakeLists.txt
  drivers/builtin/include/mbedtls/hkdf.h
  programs/psa/aead_demo.c
  programs/psa/hmac_demo.c
  programs/psa/key_ladder_demo.c
  programs/psa/psa_hash.c
  programs/test/CMakeLists.txt
  programs/test/benchmark.c
  programs/test/which_aes.c
  tests/CMakeLists.txt
  tests/include/test/mbedtls/build_info.h
  tests/include/test/psa_test_wrappers.h
  tests/src/psa_test_wrappers.c
Labels: enhancement, needs-review, priority-very-high

#325 Privatize content in Everest headers
  drivers/everest/include/tf-psa-crypto/private/everest/Hacl_Curve25519.h
  drivers/everest/include/tf-psa-crypto/private/everest/everest.h
  drivers/everest/include/tf-psa-crypto/private/everest/x25519.h
  drivers/everest/library/Hacl_Curve25519_joined.c
Labels: size-xs, approved

#334 Hide DES error with parentheses so that generate_errors.pl skips it
  drivers/builtin/include/mbedtls/des.h
Labels: priority-high, size-xs, approved
