Repository Mbed-TLS/TF-PSA-Crypto, pull requests merged in 2025-03, with the labels that each got.

#187 PR template checklist: add lines for backports
  .github/pull_request_template.md
Labels: needs-review, needs-reviewer, priority-medium, size-xs

#151 Add various configuration components
  tests/configs/user-config-for-test.h
  tests/configs/user-config-malloc-0-null.h
  tests/scripts/components-configuration.sh
Labels: enhancement, priority-high, approved

#175 [tf-psa-crypto] Remove DHM module
  docs/driver-only-builds.md
  drivers/builtin/include/mbedtls/dhm.h
  drivers/builtin/src/dhm.c
  drivers/builtin/src/psa_crypto_ffdh.c
  include/psa/crypto_config.h
  include/tf-psa-crypto/check_config.h
  programs/test/benchmark.c
  tests/suites/test_suite_dhm.data
  tests/suites/test_suite_dhm.function
Labels: size-s, needs-review, priority-high

#193 Fix link to PSA Crypto API
  README.md
Labels: enhancement, needs-review, needs-ci

#183 [tf-psa-crypto] Add components to components-build-system.sh
  tests/scripts/components-build-system.sh
Labels: size-s, needs-review, priority-high

#192 Remove Everest VS2010 compatibility headers
  ChangeLog.d/remove-everest-vs2010-compat-headers.txt
  drivers/everest/include/everest/kremlin/c_endianness.h
  drivers/everest/include/everest/kremlin/internal/callconv.h
  drivers/everest/include/everest/vs2013/inttypes.h
  drivers/everest/include/everest/vs2013/stdbool.h
Labels: bug, needs-review, priority-high, size-xs

#182 Remove RNG parameters from LMS
  drivers/builtin/include/mbedtls/lms.h
  drivers/builtin/src/lmots.c
  drivers/builtin/src/lmots.h
  drivers/builtin/src/lms.c
  tests/suites/test_suite_lmots.function
  tests/suites/test_suite_lms.function
Labels: size-s, priority-high, approved, api-break

#198 Document PSA's need for threading
  include/psa/crypto_config.h
Labels: bug, priority-high, size-xs, approved

#186 Fix psa_key_derivation_input_integer() not detecting bad state
  ChangeLog.d/fix-key-derive-bad-state-error.txt
  core/psa_crypto.c
  tests/suites/test_suite_psa_crypto.data
  tests/suites/test_suite_psa_crypto.function
Labels: priority-medium, size-xs, approved

#195 core: Allow enabling one volatile/builtin key
  core/psa_crypto_slot_management.c
Labels: bug, priority-medium, approved, needs-backports

#194 Remove RNG from x509 and PK
  drivers/builtin/include/mbedtls/pk.h
  drivers/builtin/src/pk.c
  drivers/builtin/src/pk_ecc.c
  drivers/builtin/src/pk_internal.h
  drivers/builtin/src/pk_wrap.c
  drivers/builtin/src/pk_wrap.h
  drivers/builtin/src/pkparse.c
  tests/suites/test_suite_pk.function
  tests/suites/test_suite_pkparse.function
  tests/suites/test_suite_pkwrite.function
Labels: approved, api-break

#132 Make legacy declarations private: macro guard
  docs/4.0-migration-guide/private-decls.md
  docs/4.0-migration-guide/private-decls/00README
  drivers/builtin/include/mbedtls/private_access.h
  programs/test/benchmark.c
Labels: priority-high, size-xs, approved

#213 [tf-psa-crypto] Remove MBEDTLS_PSA_INJECT_ENTROPY
  .gitignore
  ChangeLog.d/remove-inject-entropy.txt
  core/psa_crypto.c
  core/psa_crypto_storage.c
  core/psa_crypto_storage.h
  include/psa/crypto_config.h
  include/psa/crypto_extra.h
  include/tf-psa-crypto/check_config.h
  scripts/config.py
  tests/configs/user-config-for-test.h
  tests/include/test/psa_test_wrappers.h
  tests/src/psa_test_wrappers.c
  tests/suites/test_suite_entropy.function
  tests/suites/test_suite_psa_crypto_entropy.data
  tests/suites/test_suite_psa_crypto_entropy.function
  tests/suites/test_suite_psa_crypto_init.data
  tests/suites/test_suite_random.function
Labels: needs-review, priority-high

#239 Remove trailing line to fix code style
  tests/suites/test_suite_psa_crypto_entropy.function
Labels: single-reviewer, approved

#241 Fix release component names
  tests/scripts/components-sanitizers.sh
Labels: enhancement, needs-review, needs-reviewer, priority-high
